### ISSUE TITLE
Server start crash issue

### ISSUE THREAD

**Issue by solarblindfull** [quek04/The-Undergarden#11]
Hello ! I founded a "client code" issue that make my server crash at the starting. I'm on Forge 31.2.30.

Here the log :

<details>
  <summary>Crash report</summary>
  
---- Minecraft Crash Report ----
// There are four lights!

Time: 18/07/20 13:50
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	The Undergarden (undergarden) has failed to load correctly
§7Attempted to load class quek/undergarden/client/ClientStuff for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.redirect$zzc000$begin(DedicatedServer.java:746) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.customservermsgs.json:MixinDedServer,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.customservermsgs.json:MixinDedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:mixins.customservermsgs.json:MixinMCServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world.MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.9.0-12-amd64
	Java Version: 1.8.0_202, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 326602680 bytes (311 MB) / 876044288 bytes (835 MB) up to 31136546816 bytes (29694 MB)
	CPUs: 32
	JVM Flags: 22 total; -Xms512M -XX:PermSize=384M -XX:MaxPermSize=768M -XX:-UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseLargePages -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:MaxGCPauseMillis=50 -XX:ParallelGCThreads=2
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.30.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.30.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.30
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.3.1
		kotlinfml@1.5.2
    
</details>

**Comment by quek04** [comment]
i fixed that just now, hopefully.

**Comment by solarblindfull** [comment]
Thank very much for the quick fix !
