### ISSUE TITLE
Tags sometimes fail to register early enough? [1.18.1]

### ISSUE THREAD

**Issue by CDAGaming** [quek04/The-Undergarden#127]
```
Caused by: com.google.gson.JsonParseException: Error loading registry data: Unknown tag: undergarden:base_stone_undergarden; Unknown tag: undergarden:base_stone_undergarden; Unknown tag: undergarden:base_stone_undergarden; Unknown tag: undergarden:shiverstone_ore_replaceables; Unknown tag: undergarden:depthrock_ore_replaceables; Unknown tag: undergarden:shiverstone_ore_replaceables; Unknown tag: undergarden:depthrock_ore_replaceables; Unknown tag: undergarden:tremblecrust_ore_replaceables; Unknown tag: undergarden:shiverstone_ore_replaceables; Unknown tag: undergarden:depthrock_ore_replaceables; Unknown tag: undergarden:shiverstone_ore_replaceables; Unknown tag: undergarden:depthrock_ore_replaceables; Unknown tag: undergarden:shiverstone_ore_replaceables; Unknown tag: undergarden:base_stone_undergarden; Unknown tag: undergarden:shiverstone_ore_replaceables; Unknown tag: undergarden:depthrock_ore_replaceables; Unknown tag: undergarden:shiverstone_ore_replaceables; Unknown tag: undergarden:depthrock_ore_replaceables; Unknown tag: undergarden:depthrock_ore_replaceables
	at net.minecraft.core.RegistryAccess.m_175498_(RegistryAccess.java:156) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.core.RegistryAccess.m_175503_(RegistryAccess.java:155) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.core.RegistryAccess.m_175500_(RegistryAccess.java:146) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.resources.RegistryReadOps.m_195841_(RegistryReadOps.java:37) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.core.RegistryAccess.m_123086_(RegistryAccess.java:104) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100898_(CreateWorldScreen.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList.m_101676_(WorldSelectionList.java:103) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList.<init>(WorldSelectionList.java:85) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_7856_(SelectWorldScreen.java:65) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:422) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:916) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_169449_(TitleScreen.java:147) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.TitleScreen.m_6375_(TitleScreen.java:345) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%23178!/:?]
	... 24 more
```

This crash does not always occur, only maybe a few times out of a dozen this crash will occur when attempting to make a new world or join a server.

**Comment by quek04** [comment]
1.18.1 unsupported
