### ISSUE TITLE
Recent Update Crashes on Startup 'NoSuchFieldError'

### ISSUE THREAD

**Issue by KakashoLin** [quek04/The-Undergarden#179]
Updating to the latest update you encounter an error on startup. 

"net.minecraftforge.fml.ModLoadingException: The Undergarden (undergarden) encountered an error during the common_setup event phase
§7java.lang.NoSuchFieldError: STEP_HEIGHT
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.20.1-47.2.0.jar%231046!/:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.2.0.jar%231045!/:?] {}"

[crash-2024-02-15_23.10.02-client.txt](https://github.com/quek04/The-Undergarden/files/14306138/crash-2024-02-15_23.10.02-client.txt)

**Comment by GizmoTheMoonPig** [comment]
youre gonna have to use neoforge for now, the field is named differently on forge
