### ISSUE TITLE
Catacombs not on structure map

### ISSUE THREAD

**Issue by TheRedNeckGamer** [quek04/The-Undergarden#71]
[16/01/2021 00:52:40 AM] ****************** Blame Report 1.9.0 ******************
[16/01/2021 00:52:40 AM] 
[16/01/2021 00:52:40 AM]  A crash is most likely going to happen right after this report!
[16/01/2021 00:52:40 AM]  It seems undergarden:catacombs | undergarden:catacombs is the cause because it is not added 
[16/01/2021 00:52:40 AM]  to the FlatGenerationSettings.STRUCTURES map. Please let the mod owner 
[16/01/2021 00:52:40 AM]  of that structure know about this crash. That way they can add their structure 
[16/01/2021 00:52:40 AM]  to that map since someone is trying to spawn it in a flat/custom dimension. 
[16/01/2021 00:52:40 AM] 
[16/01/2021 00:52:40 AM] 
[16/01/2021 00:52:40 AM] [00:52:40] [Render thread/ERROR]: Exception reading **USERSDIR**\instances\TheBeastGetsBigger\saves\New World\level.dat
[16/01/2021 00:52:40 AM] java.lang.NullPointerException: null
[16/01/2021 00:52:40 AM] 	at net.minecraft.world.biome.BiomeGenerationSettings.lambda$getStructure$8(BiomeGenerationSettings.java:86) ~[?:?]
[16/01/2021 00:52:40 AM] 	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:40 AM] 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:40 AM] 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:40 AM] 	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:40 AM] 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:40 AM] 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:40 AM] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:41 AM] 	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:41 AM] 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:41 AM] 	at java.util.stream.ReferencePipeline.findAny(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:41 AM] 	at net.minecraft.world.biome.BiomeGenerationSettings.func_242491_a(BiomeGenerationSettings.java:87) ~[?:?]
[16/01/2021 00:52:41 AM] 	at net.minecraft.world.gen.FlatGenerationSettings.func_236942_c_(FlatGenerationSettings.java:151) ~[?:?]
[16/01/2021 00:52:41 AM] 	at net.minecraft.world.gen.FlatChunkGenerator.<init>(SourceFile:26) ~[?:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.datafixers.util.Either$Left.mapBoth(Either.java:33) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.DataResult.map(DataResult.java:110) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.MapDecoder$4.decode(MapDecoder.java:94) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$null$1(KeyDispatchCodec.java:67) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$decode$2(KeyDispatchCodec.java:58) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.codecs.KeyDispatchCodec.decode(KeyDispatchCodec.java:56) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:41 AM] 	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:249) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at net.minecraftforge.common.LenientUnboundedMapCodec.lambda$decode$3(LenientUnboundedMapCodec.java:52) ~[forge:?]
[16/01/2021 00:52:42 AM] 	at java.util.stream.ReduceOps$1ReducingSink.accept(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at java.util.stream.ReferencePipeline.reduce(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:42 AM] 	at net.minecraftforge.common.LenientUnboundedMapCodec.decode(LenientUnboundedMapCodec.java:48) ~[forge:?]
[16/01/2021 00:52:42 AM] 	at net.minecraftforge.common.LenientUnboundedMapCodec.lambda$decode$8(LenientUnboundedMapCodec.java:70) ~[forge:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at net.minecraftforge.common.LenientUnboundedMapCodec.decode(LenientUnboundedMapCodec.java:70) ~[forge:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at net.minecraft.util.registry.SimpleRegistryCodec.decode(SourceFile:33) ~[?:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.Decoder$2.decode(Decoder.java:63) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.decode(RecordCodecBuilder.java:324) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:42 AM] 	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.Decoder$1.decode(Decoder.java:49) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.Decoder.decode(Decoder.java:22) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at com.mojang.serialization.Decoder.parse(Decoder.java:26) ~[datafixerupper-4.0.26.jar:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.world.storage.SaveFormat.func_237259_a_(SaveFormat.java:99) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.world.storage.SaveFormat.lambda$getReader$4(SaveFormat.java:197) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.world.storage.SaveFormat.func_237266_a_(SaveFormat.java:158) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.world.storage.SaveFormat.access$400(SaveFormat.java:63) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237284_a_(SaveFormat.java:324) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.Minecraft.func_238181_a_(Minecraft.java:1672) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.Minecraft.func_238189_a_(Minecraft.java:1860) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.Minecraft.func_238195_a_(Minecraft.java:1711) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.Minecraft.func_238191_a_(Minecraft.java:1681) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214443_e(SourceFile:407) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214438_a(SourceFile:317) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_231044_a_(SourceFile:259) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.gui.widget.list.AbstractList.func_231044_a_(AbstractList.java:309) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?]
[16/01/2021 00:52:43 AM] 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
[16/01/2021 00:52:43 AM] 	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
[16/01/2021 00:52:43 AM] 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
[16/01/2021 00:52:43 AM] 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
[16/01/2021 00:52:43 AM] 	at net.minecraft.client.main.Main.main(Main.java:184) ~[client-1.16.4.jar:?]
[16/01/2021 00:52:43 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
[16/01/2021 00:52:43 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:43 AM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:43 AM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
[16/01/2021 00:52:43 AM] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.36.jar:35.1]
[16/01/2021 00:52:43 AM] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
[16/01/2021 00:52:43 AM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
[16/01/2021 00:52:43 AM] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
[16/01/2021 00:52:43 AM] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
[16/01/2021 00:52:43 AM] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
[16/01/2021 00:52:43 AM] [00:52:40] [Render thread/ERROR]: 
[16/01/2021 00:52:44 AM] ****************** Blame Report 1.9.0 ******************

**Comment by remplerus** [comment]
already discussed here #60

**Comment by TheRedNeckGamer** [comment]
Incorrect. These are two separate issues caused by two separate methods within one mod. but okay.

**Comment by TheRedNeckGamer** [comment]
To be more specific, mine was caused by an initial loading, whereas they were able to play, then exit, then unable to load again. I was simply unable to load. Both issues had a connection, sure, through the structure map, however, they were caused by completely separate operations.

**Comment by remplerus** [comment]
fyi: https://gist.github.com/remplerus/f6423a1c39a287e429b68a49a4e6fd76
that's what i posted there and is also the same issue.

**Comment by TheRedNeckGamer** [comment]
You're kinda correct, but also not. They've got the same root cause, however, they're two separate issues. Blame report has a way of hiding the method (unfortunately) that caused the issue within the mod by showing us more information about what mojang's code disagreed with. As you get deeper into the crash report, you'll see they're not the same issue. two separate issues, one cause. Idk it's kinda hard to explain but the jist is that there's one underlying cause to two seperate problems. 

Let's try this... hypothetically you're sick... you've got the flu.
The flu causes you to have a high fever, which is an issue and can be alleviated by taking aspirin, but it also causes nausea which most assuredly cannot be fixed by taking an aspirin. the point is the aspirin you took for the headache didn't get rid of the flu, it got rid of one issue.
