### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by jumlock** [quek04/The-Undergarden#88]
I'm running a modpack which has quite a few mods.
I discovered today that Mowzies Mobs caused a Tick rate crash when entering The Undergarden dimension.

Description: Exception ticking world

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at com.bobmowzie.mowziesmobs.server.entity.MowzieEntity.func_213380_a(MowzieEntity.java:107) ~[?:1.5.14] {re:classloading}
	at com.bobmowzie.mowziesmobs.server.entity.grottol.EntityGrottol.func_213380_a(EntityGrottol.java:195) ~[?:1.5.14] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234974_a_(WorldEntitySpawner.java:247) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinEntityWorldSpawner,pl:mixin:A}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:173) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinEntityWorldSpawner,pl:mixin:A}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinEntityWorldSpawner,pl:mixin:A}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:enhancedcelestials.mixins.json:MixinEntityWorldSpawner,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(ServerChunkProvider.java:359) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$16180/595562330.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {re:computing_frames}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:346) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:321) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:good_nights_sleep.mixins.json:MinecraftServerMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$15536/509170117.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

I removed Mowzies Mobs and the dimension now works fine.

**Comment by Fooshcookie** [comment]
Disable the Grottol in the Mowzie's config, and it will run fine, that's a Mowzie's issue, not an Undergarden one. The same thing happens in the Twilight Forest Alpha Build. Nothing we can do about it, really, unless there is something I'm missing.

This link here is a report of the issue, and it appears Mowzie is already aware.  https://github.com/BobMowzie/MowziesMobs/issues/331 I'm certain there will be a fix soon enough from their end, until then, just disable the Grottol. 

Edit: The TF Alpha build is still getting an issue with Mowzies, not going to report as the mod isn't out yet and is still being worked on. So, you may have to completely disable Mowzies, or simply not use UG. I'm not sure what the issue fully is.

**Comment by quek04** [comment]
this is not an undergarden issue
